### ISSUE TITLE
Footer not sticked to the end

### ISSUE THREAD

**Issue by KlausMikhaelson** [Dun-sin/HearItFresh#1]
Hey so I just saw that footer is not sticked to the end of the page which is not a big issue but ig it's just better if it's there sticked to the end of the page ?
<img width="960" alt="image" src="https://user-images.githubusercontent.com/100528412/218449058-218bc77a-fef7-4b19-a3ad-3cb17a43cd04.png">
would love to work on it incase you think this should be fixed and it's an issue !
Thank you !

**Comment by Dun-sin** [comment]
Hi, thanks for raising an issue, feel free to make a PR. Thank you🙌🏽

**Comment by gambhirsharma** [comment]
Can I take over this task @KlausMikhaelson?

**Comment by KlausMikhaelson** [comment]
Hey @gambhirsharma I'm working on it rn, would really appreciate if you can pick up other issues !

**Comment by KlausMikhaelson** [comment]
Hey @gambhirsharma I'm kinda busy rn and not able to fix it idk why css just s#ks for me lol, please take it if you want to !

**Comment by gambhirsharma** [comment]
> Hey @gambhirsharma I'm kinda busy rn and not able to fix it idk why css just s#ks for me lol, please take it if you want to !

Done!!

**Comment by gambhirsharma** [comment]
@KlausMikhaelson 
Changed the overflow from scroll to hidden and it solved all the problems.
