### ISSUE TITLE
Revamp landing page look

### ISSUE THREAD

**Issue by d-kens** [Dun-sin/HearItFresh#10]
Proposing a new look for the initial page.

## Initial page
![Screenshot (7)](https://user-images.githubusercontent.com/98984075/221190617-0302c58d-8170-46df-9b41-649b262efa1a.png)

## After Logging in
![Screenshot (8)](https://user-images.githubusercontent.com/98984075/221190702-a8ad62d1-3f4c-448e-8664-22eddb2c60f6.png)

**Comment by Dun-sin** [comment]
Hi @d-kens thanks for this, looks better than mine, but what's the UI When someone picks a choice

**Comment by d-kens** [comment]
Well, I didn't get to work on that one.

**Comment by d-kens** [comment]
or look into it

**Comment by Dun-sin** [comment]
You don't need to actual code it, but the landing page has a link to the other pages, hence why the button is at the top not the bottom. I'm trying to see how your idea works better than mine

**Comment by d-kens** [comment]
Whether it's at the top or bottom doesn't make much of a different really. What I was aiming at is displaying the options buttons after connecting to a Spotify account.

**Comment by d-kens** [comment]
Rather than having them blurred and behind the actual content we want to display on the initial page.

**Comment by Dun-sin** [comment]
> Whether it's at the top or bottom doesn't make much of a different really. What I was aiming at is displaying the options buttons after connecting to a Spotify account.

I understand that, your aim is much short sighted and not looking into accounts other things, hence why I asked if you looked at other things

**Comment by d-kens** [comment]
Think about it, the button (logout) being at the top makes it the first thing that the user sees before even seeing the buttons for selecting options. Having the buttons at the bottom makes more sense if we are to respect visual hierarchy. After they connect their Spotify, they see that they can select an option based on what they want and finally the logout button . 

Its more of what do we want the user to see first in these different pages. Making them see that they can actually select an option before having to interact with logout button.

**Comment by Dun-sin** [comment]
> Think about it, the button (logout) being at the top makes it the first thing that the user sees before even seeing the buttons for selecting options. Having the buttons at the bottom makes more sense if we are to respect visual hierarchy. After they connect their Spotify, they see that they can select an option based on what they want and finally the logout button .
> 
> Its more of what do we want the user to see first in these different pages. Making them see that they can actually select an option before having to interact with logout button.

I can't think about it😂 I can't see your idea in my head unless you have a design. Do you know how to use figma?
