### ISSUE TITLE
[OTHER] delete pnpm-lock.yaml

### ISSUE THREAD

**Issue by Dun-sin** [Dun-sin/HearItFresh#24]
> Note: Make sure to read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/HearItFresh/blob/main/CONTRIBUTING.md)

**Comment by RajatX24** [comment]
Hello @Dun-sin ,

I would like to work on this. Please assign it to me.

**Comment by Dun-sin** [comment]
> Hello @Dun-sin ,
> 
> I would like to work on this. Please assign it to me.

sure

**Comment by RajatX24** [comment]
Hello @Dun-sin ,

I have created a PR for this issue.
You can check it out here:https://github.com/Dun-sin/HearItFresh/pull/27

Please let me know if there are any changes to be made.
If merging, please add the label hacktoberfest-accepted while merging. I would be grateful.

Thanks.
