### ISSUE TITLE
[DOCS]: add PR and Issue templates

### ISSUE THREAD

**Issue by Dun-sin** [Dun-sin/HearItFresh#4]
Add Pull Request or Issue templates for when someone makes a pull request or tries to create an issue.
- Use this already made template as your guide for the PR template → [Template Link](https://github.com/Dun-sin/Code-Magic/blob/main/.github/pull_request_template.md)
- Use this already made template as your guide for the Issue templates → [Template Link](https://github.com/Dun-sin/Code-Magic/tree/main/.github/ISSUE_TEMPLATE)

Just edit the necessary things.

### comment to be assigned to this, just don't work on it without asking

**Comment by mithindev** [comment]
Can I work on this too ?

**Comment by Dun-sin** [comment]
> Can I work on this too ?

Sure, but don't use chatgpt instead, actually read through the issue and do it properly. Thank you🤞🏽🚀

**Comment by mithindev** [comment]
Yeah sure.

**Comment by Dun-sin** [comment]
Hi @mithindev this doesn't take up too an hour to do either, can you get it done before the day is over?

**Comment by mithindev** [comment]
Ok, I will finish it before today. I am actually in the middle of my exams. I will do it today evening.

**Comment by Dun-sin** [comment]
> Ok, I will finish it before today. I am actually in the middle of my exams. I will do it today evening.

No problem and good luck on your exams
