### ISSUE TITLE
Playlist is empty....

### ISSUE THREAD

**Issue by mad4some** [Dun-sin/HearItFresh#5]
Hello, I just tried this out twice by signing into spotify > pasting a playlist > click "get songs" > I could see the program running and going thru the steps to create new playlist > went back to my spotify and there were the 2 new HearItFresh playlists but when I open either one, there's no songs and the playlist is empty.

**Comment by Dun-sin** [comment]
I'm sorry you had to experience that, for me to understand why wrong, can you provide the input you gave to it, so I can use that to debug.

Also, an important factor could also be how strong your network is, it seems the problem happened when Spotify was trying to add the songs to the Playlist.

But either way, just let me know the input you gave to it. Thank you and sorry again.

**Comment by mad4some** [comment]
Hey Dunsin, input was >
https://open.spotify.com/playlist/1VrdAH3LzGpjsTaZwYI7hp
I have fast internet with NO speed or connection problems....
I thought it might be because I had the playlist as "private", but I
changed it to "public" and it did the same thing...I log in, I paste
playlist address, I watch the program fetch the songs and then create new
songs and then it creates the new playlist properly in my spotify. But when
I open it either on the website or the desktop player....the list is empty
with no songs. 😭 Thanks, Mark

**Comment by Dun-sin** [comment]
Yes, I figured out that pasting a Playlist doesn't work, bear with me for a while more. I will fix it and add new features.

**Comment by mad4some** [comment]
Thank you Dunsin!.....and thanks for your work!

**Comment by Dun-sin** [comment]
Hi @mad4some it's fixed. Thanks for being patience with it
