### ISSUE TITLE
Make the  website more Mobile friendly.

### ISSUE THREAD

**Issue by gambhirsharma** [Dun-sin/HearItFresh#7]
## Issue
Once you open the website on Mobile. The footer and header looked messed up.
The rest of the website is mobile-friendly but the footer and header need some improvement.

## Screenshot
![image](https://user-images.githubusercontent.com/69895353/219549105-432d82c3-b006-49c9-b8ac-d80d3254895e.png)

## Solution
* For Header
  Make the text-align centre when it's in mobile mode.

* For Footer
  Disable the text or reduce it in mobile mode. 
  or
  Make the items align vertically.

**Comment by Dun-sin** [comment]
You should probably do a git pull

**Comment by gambhirsharma** [comment]
> You should probably do a git pull

Oups 😅

But i still think there is scope in improving the UI. Its looking messy in mobile mode. The desktop mode is awesome but... 
Let me send you some figma prototypes in a while.

**Comment by Dun-sin** [comment]
> > You should probably do a git pull
> 
> Oups 😅
> 
> But i still think there is scope in improving the UI. Its looking messy in mobile mode. The desktop mode is awesome but... 
> Let me send you some figma prototypes in a while. 

Looks pretty neat to me

**Comment by gambhirsharma** [comment]
If you are OK with the design then its fine. I think I am overthink about the design, so sorry for that.😅

You can close this issue if you want coz i don't have anything more to add.

**Comment by Dun-sin** [comment]
> If you are OK with the design then its fine. I think I am overthink about the design, so sorry for that.😅
> 
> You can close this issue if you want coz i don't have anything more to add. 

😂✌🏽 Understandable, if you have something more specific you can create another issue on that
